obstacle_range: 3.0 #Default 3.0
raytrace_range: 3.5 #Default 3.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

inflation_radius: 1.75 #default 1.0
cost_scaling_factor: 2.58 #default 3.0

#min_obstacle_height: -0.5 #Default not here

map_type: costmap
observation_sources: scan
scan: {sensor_frame: Bot2/base_scan, data_type: LaserScan, topic: Bot2/scan, marking: true, clearing: true}

